### ISSUE TITLE
requirements are incomplete

### ISSUE THREAD

**Issue by Lii-Yan** [open-mmlab/PowerPaint#1]
some modules likes mmcv mmgic  are not mentioned in requirements

**Comment by zhuang2002** [comment]
> some modules likes mmcv mmgic are not mentioned in requirements

Thanks for your attention! The repository has been updated.

**Comment by tranquan687** [comment]
> some modules likes mmcv mmgic are not mentioned in requirements

try this, it works for me
https://github.com/zhuang2002/PowerPaint/issues/23#issue-2206231108
