### ISSUE TITLE
where are the training codes?

### ISSUE THREAD

**Issue by huangjch526** [open-mmlab/PowerPaint#11]
Thanks for your work. Will the training code be open source?

**Comment by learn01one** [comment]
+1

**Comment by grainw** [comment]
+1

**Comment by igodogi** [comment]
+1

**Comment by rubymiaomiao** [comment]
+1

**Comment by lovejing0306** [comment]
+1

**Comment by zengyh1900** [comment]
Hi @huangjch526 @learn01one @grainw @igodogi @rubymiaomiao @lovejing0306 
Thank you for your interest and being so patient :)
We have released our training configurations and scripts for both [train_ppt1_sd15.py](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt1_sd15.py) for unet-based version and [train_ppt2_bn.py](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt2_bn.py) for brushnet-based version.
