### ISSUE TITLE
Some question about parameter configurations

### ISSUE THREAD

**Issue by murmurelo111** [open-mmlab/PowerPaint#14]
Hello!
Could you provide some examples of parameter configurations?I'm not quite clear on how to set the prompt for a specific task, especially for object removal.
Thanks very much!

**Comment by zengyh1900** [comment]
Hi @murmurelo111 

Thank you for being so patient. We have updated our readme with detailed instructions, please check it [here](https://github.com/open-mmlab/PowerPaint?tab=readme-ov-file#inference)
