### ISSUE TITLE
What about next plan ?

### ISSUE THREAD

**Issue by delldu** [open-mmlab/PowerPaint#15]
Thanks for your wonderful job !!!
We are looking for **"Stronger Model Weights Coming Soon！"**

**Comment by zengyh1900** [comment]
Hi @delldu 
I appreciate your patience.
We have supported `PowerPaint-v2` based on BrushNet, which requires much shorter training time and less training cost. Please check it in [readme](https://github.com/open-mmlab/PowerPaint?tab=readme-ov-file#-news)
