### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by Arcxml** [open-mmlab/PowerPaint#17]
Hello, when I try the model on huggingface https://huggingface.co/Sanster/PowerPaint-V1-stable-diffusion-inpainting/tree/main , I meet this error
<img width="1082" alt="image" src="https://github.com/zhuang2002/PowerPaint/assets/138861545/be7809fe-0190-4f7f-980c-8e143ca07e1b">

And I try to reload it, I still get this error

Could you please help me?

**Comment by STARRY2001** [comment]
I'm having the same issue, is there any solution to this? thanks！

**Comment by Arcxml** [comment]
我发现了他的另外一种实现，采用了那个实现之后没有这个报错。但是依据我的实验来看的话，这个模型的运行效果并没有理想中的那么好，经常会生成一些奇怪的人物图像。。。如果你也遇到这种问题，欢迎交流



---- Replied Message ----
| From | Zhipei ***@***.***> |
| Date | 03/13/2024 21:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [zhuang2002/PowerPaint] safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge (Issue #17) |

I'm having the same issue, is there any solution to this? thanks！

**Comment by STARRY2001** [comment]
这个报错是因为lfs没起作用，没下载权重，安装好lfs之后，直接执行`git clone https://huggingface.co/JunhaoZhuang/PowerPaint-v1/ ./models`；或者手动去huggingface上下载权重
