### ISSUE TITLE
Object removal  demo issue

### ISSUE THREAD

**Issue by anilsathyan7** [open-mmlab/PowerPaint#18]
In the demo app (openxlab) the object removal with mask changes other objects(especially complicated patters/designs) outside mask. However in the github codebase the final output is blended with original image and mask to prevent this issue. 

The in-painted regions in demo looks better(compared to alpha blended code) in the local version but unmasked objects are changed in the demo.(eg. objects with shadows)

**Comment by zengyh1900** [comment]
Hi @anilsathyan7 ,
Thanks for bringing up this issue. The changes in unmasked areas are due to the VAE image encoding process, which is unavoidable in latent diffusion models. If there are any community solutions to solve this problem, we would be happy to discuss :)
