### ISSUE TITLE
The suffix of the model file in the code is different from the suffix of the downloaded model file

### ISSUE THREAD

**Issue by zsy-code** [open-mmlab/PowerPaint#2]
I found that the diffusion model file name declared in “gradio_powerpaint” has a .bin suffix, while the file in the model card has a safetensor suffix. As shown below:
![screenshot-20231211-102835](https://github.com/zhuang2002/PowerPaint/assets/150211669/37311b00-68f3-4cca-9b91-f1b67d008af3)
![screenshot-20231211-102914](https://github.com/zhuang2002/PowerPaint/assets/150211669/9d0bb761-b301-471d-b2fb-27149afbfc6d)

**Comment by zhuang2002** [comment]
In our most recent code update, we have resolved this issue. Thank you for your attention!
