### ISSUE TITLE
Can you give me some examples how to use your remove feature ? I dont know what i need to prompt. Thanks

### ISSUE THREAD

**Issue by ngocnd2402** [open-mmlab/PowerPaint#20]

**Comment by Arcxml** [comment]
![image](https://github.com/zhuang2002/PowerPaint/assets/138861545/84930498-a212-40c0-b0e6-39c6db78c41a)
like this

**Comment by zengyh1900** [comment]
hi @ngocnd2402 
thank you for your patience. we have updated our readme with detailed instructions. https://github.com/open-mmlab/PowerPaint?tab=readme-ov-file#object-removal
