### ISSUE TITLE
 The local results are inconsistent with the online demo

### ISSUE THREAD

**Issue by grainw** [open-mmlab/PowerPaint#24]
The same picture, the same mask, the same parameters, the local results are inconsistent with the online demo (OpenXlab) results, the local always returns NSFW and a black image

**Comment by 202112213501021** [comment]
> The same picture, the same mask, the same parameters, the local results are inconsistent with the online demo (OpenXlab) results, the local always returns NSFW and a black image

Hello, did you run successfully

**Comment by ustczhouyu** [comment]
> The same picture, the same mask, the same parameters, the local results are inconsistent with the online demo (OpenXlab) results, the local always returns NSFW and a black image

Hi, have you solved this problem? Can you tell me how you outpainting locally?
