### ISSUE TITLE
About training code

### ISSUE THREAD

**Issue by Tangcj1226** [open-mmlab/PowerPaint#28]
Thanks for your great work! 
Can you publish the training code ? 
I want to train it on SDXL.

**Comment by wangupupup** [comment]
+1

**Comment by zhLawliet** [comment]
+1

**Comment by lovejing0306** [comment]
+1

**Comment by WenmuZhou** [comment]
+1

**Comment by RunpuWei** [comment]
+1

**Comment by zengyh1900** [comment]
hi @WenmuZhou @Tangcj1226 @wangupupup @zhLawliet @lovejing0306 @RunpuWei 

Thank you for your interest and being so patient :)
We have released our training configurations and scripts for both [train_ppt1_sd15.py](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt1_sd15.py) for unet-based version and [train_ppt2_bn.py](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt2_bn.py) for brushnet-based version.

**Comment by wangupupup** [comment]
> hi @WenmuZhou @Tangcj1226 @wangupupup @zhLawliet @lovejing0306 @RunpuWei
> 
> Thank you for your interest and being so patient :) We have released our training configurations and scripts for both [train_ppt1_sd15.py](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt1_sd15.py) for unet-based version and [train_ppt2_bn.py](https://github.com/open-mmlab/PowerPaint/blob/dev/train_ppt2_bn.py) for brushnet-based version.

wow， thank you！

**Comment by justStarG** [comment]
very cool, does it support sdxl？will it support flux dev？

**Comment by WenmuZhou** [comment]
Can this script be used for fine-tuning the trained PowerPaint model with LoRA?
