### ISSUE TITLE
No Clear Instruction to Run in Windows

### ISSUE THREAD

**Issue by NunuChan123** [open-mmlab/PowerPaint#31]
**Hi I am not familiar with coding but I do use several GitHub tools. For some reason I couldn't set up this project in my windows. Any help will be kind.**

**So far what I did was**

1. Clone the Repository:
   - I opened my terminal or command prompt.
   - Navigated to the directory where I wanted to store the PowerPaint repository.
   - Ran the following command to clone the repository:
     
     git clone https://github.com/zhuang2002/PowerPaint.git
     

2. Navigate to the Repository:
   - Changed my working directory to the newly cloned PowerPaint folder:
     
     cd PowerPaint
     

3. Create a Virtual Environment (Optional):
   - If I preferred using virtual environments (recommended), I created one using Conda:
     
     conda create --name PowerPaint python=3.9
     
   - Activated the virtual environment:
     
     conda activate PowerPaint
     

4. Install Dependencies:
   - Installed the required Python packages by running:
     
     pip install -r requirements.txt
     

5. Run PowerPaint v2:
   - Executed the following command to start PowerPaint v2:
     
     python gradio_PowerPaint_BrushNet.py
     

6. Create a Models Folder:
   - Inside the PowerPaint directory, created a folder named models:
     
     mkdir models
     

7. Set up Git LFS (Large File Storage):
   - Installed Git LFS if not already installed:
     
     git lfs install
     

8. Clone the PowerPaint Model:
   - Fetched the pre-trained PowerPaint model using Git LFS:
     
     git lfs clone https://huggingface.co/JunhaoZhuang/PowerPaint-v1/ ./models
     

I'm stuck here. Can you help me with the next steps?

**Comment by zengyh1900** [comment]
sorry, we do not support on windows
