### ISSUE TITLE
Powerpaint V2 Not Starting

### ISSUE THREAD

**Issue by RFedz007989** [open-mmlab/PowerPaint#38]
Hi,

I am getting this error when starting Powerpaint V2 : (python gradio_PowerPaint_BrushNet.py)

Kindly check this error.

(C:\Powerpaint\PowerPaint>python gradio_PowerPaint_BrushNet.py
C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\Powerpaint\PowerPaint\gradio_PowerPaint_BrushNet.py", line 14, in <module>
    from utils.utils import TokenizerWrapper, add_tokens
  File "C:\Powerpaint\PowerPaint\utils\utils.py", line 9, in <module>
    from mmagic.utils import try_import
ModuleNotFoundError: No module named 'mmagic')

Thank You

**Comment by danielscos** [comment]
You don't have the mmagic module. Run : pip install mmagic

**Comment by RFedz007989** [comment]
> You don't have the mmagic module. Run : pip install mmagic

Thanks, I installed, as you said, but after that I got this below mentioned error. Pls check.

(C:\Powerpaint\PowerPaint>python gradio_PowerPaint_BrushNet.py
C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\Powerpaint\PowerPaint\gradio_PowerPaint_BrushNet.py", line 14, in <module>
    from utils.utils import TokenizerWrapper, add_tokens
  File "C:\Powerpaint\PowerPaint\utils\utils.py", line 9, in <module>
    from mmagic.utils import try_import
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\mmagic\__init__.py", line 35, in <module>
    assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
AssertionError: mmcv==2.0.0rc4 is used but incompatible. Please install mmcv-full>=[2, 0, 0], <[2, 2, 0]

Thank You

**Comment by danielscos** [comment]
Run pip uninstall mmcv, and then run pip install mmcv ==2.0.0

**Comment by danielscos** [comment]
You really don't need people to solve this for you. Just look at the end of the log, it says a certain module isn't installed or is not the correct version, and just install the module yourself lol

**Comment by RFedz007989** [comment]
I asked this here, as I was getting the same error again & again of this even after installing via pip (AssertionError: mmcv==2.0.0rc4 is used but incompatible. Please install mmcv-full>=[2, 0, 0], <[2, 2, 0] )

Now also after again uninstall & install via PIP, still getting the same error mention above.

Thank You

**Comment by lijiaxing0213** [comment]
@RFedz007989 How about specifying these library versions? My environment is set up like this:

> mmagic: 1.2.0
> mmcv: 2.1.0
> mmengine: 0.10.3

The installation process reported no errors. For reference, you can check the documentation: https://mmcv.readthedocs.io/en/latest/get_started/installation.html

**Comment by zengyh1900** [comment]
Hi @RFedz007989, 

Thanks for your attention. Are you using PowerPaint from this [repo](https://github.com/open-mmlab/powerpaint) directly? 
I have installed and checked it again. I think we don't need to install mmcv, mmagic and mmengine. 

BTW, we have updated the readme and refactored the codes to make it clear. Please check it and any feedback are welcome :)
