### ISSUE TITLE
Removal Bug

### ISSUE THREAD

**Issue by lanson07** [open-mmlab/PowerPaint#39]
Hi，i try the case in the paper and i find that the removal case shown in paper is not  reproduced
Can u give me some advises to fix it. Thx!

**Comment by lanson07** [comment]
![企业微信截图_17159324028294](https://github.com/open-mmlab/PowerPaint/assets/29429038/f6809676-6a39-46c7-b726-b85664971b98)

**Comment by zhuang2002** [comment]
This phenomenon arises from the fact that during training, empty texts were occasionally paired with object masks, leading to a bias in the model towards generating objects. To mitigate this issue, training the model exclusively with empty texts mapped to random masks (which better aligns with the characteristic of empty texts representing unconditional branches) can be implemented. In the coming days, we will release an open-source model that addresses certain issues present in the current v2 model.

**Comment by dydxdt** [comment]
> This phenomenon arises from the fact that during training, empty texts were occasionally paired with object masks, leading to a bias in the model towards generating objects. To mitigate this issue, training the model exclusively with empty texts mapped to random masks (which better aligns with the characteristic of empty texts representing unconditional branches) can be implemented. In the coming days, we will release an open-source model that addresses certain issues present in the current v2 model.

Looking forward to the new model! I have another question that I found that the generated images are always blurrer than the input image though the result is good and consistent (for outpainting tasks). Do you have any advice for improving the image quality of the original regions? Thx very much. 
@zhuang2002

**Comment by WenmuZhou** [comment]
I also noticed that the generated image will be a little darker than the original image. How to solve this?

**Comment by lanson07** [comment]
> This phenomenon arises from the fact that during training, empty texts were occasionally paired with object masks, leading to a bias in the model towards generating objects. To mitigate this issue, training the model exclusively with empty texts mapped to random masks (which better aligns with the characteristic of empty texts representing unconditional branches) can be implemented. In the coming days, we will release an open-source model that addresses certain issues present in the current v2 model.

Thx for your works! 
I find the latest version of weights are released (V2.1) and I try the object removal with the same cake photo above. But the result is still wrong. Is there any other tips to figure this phenomenon ?

**Comment by lanson07** [comment]
> I also noticed that the generated image will be a little darker than the original image. How to solve this?

I meet the same question! Do you fix it?  @zhuang2002 @WenmuZhou
