### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by danielscos** [open-mmlab/PowerPaint#40]
The tutorial to get started with PowerPaint V2 locally is not clear. I've been trying for several months now, but I always get cuda errors (I have an Rtx Card and a powerful CPU).
Please do a detailed instruction of how to run PowerPaint V2 locally.

**Comment by zengyh1900** [comment]
Hi @danielscos, 

Thanks for your suggestions. We have updated the readme with a detailed instruction and also refactor the codes to make it clearer. Would you mind checking it again? 

Any suggestions and further discussions are always welcome :)

**Comment by danielscos** [comment]
Hi @zengyh1900 !

Thank you for your response, and for considering updating the instructions.
I will definitely check it now, and tell you if it works/how I liked it.
