### ISSUE TITLE
meet error in load v1 text_encoder.safetensors

### ISSUE THREAD

**Issue by WenmuZhou** [open-mmlab/PowerPaint#41]
my scripts is  python gradio_PowerPaint.py

![image](https://github.com/open-mmlab/PowerPaint/assets/12406017/fa46dbbe-e4a8-457d-997f-6be9e32dd0b9)

**Comment by lijiaxing0213** [comment]
It looks like an issue with the model weights. Try manually downloading from https://huggingface.co/JunhaoZhuang/PowerPaint-v1 and then modify the path.

**Comment by WenmuZhou** [comment]
I downloaded the model directly from here, and I would encounter this problem. After I added the parameter of strict=False, it could be loaded normally.
