### ISSUE TITLE
Some questions about Prompt

### ISSUE THREAD

**Issue by WenmuZhou** [open-mmlab/PowerPaint#44]
Hello, I have a few questions about the prompt words in the code and paper. I hope you can help me solve them.

1. text-guided

The prompt for the text-guided task in the paper should only be P_obj,
! [image] (https://github.com/open-mmlab/PowerPaint/assets/12406017/5c399d7f-94f2-4e24-a0fc-2cb18805c3df)

But in the code, it does add P_obj in the negative_prompt, why is this?

https://github.com/open-mmlab/PowerPaint/blob/main/gradio_PowerPaint_BrushNet.py#L101-L104

2. shake-guided

There is a fitting_degree parameter in the code to adjust the weight between shape and text, but in [Code](https://github.com/open-mmlab/PowerPaint/blob/main/gradio_PowerPaint_BrushNet.py#L91-L94), promptA, promptB and negative_promptA, negative_promptB are set to the same value, and, when performing weight addition, the code is as follows

```
prompt_embeds = prompt_embedsA * (t) + (1 - t) * prompt_embedsB #https://github.com/open-mmlab/PowerPaint/blob/main/pipeline/pipeline_PowerPaint_Brushnet_CA.py#L345

negative_prompt_embeds = negative_prompt_embedsA [0] * (t_nag) + (1 - t_nag) * negative_prompt_embedsB [0] #https://github.com/open-mmlab/PowerPaint/blob/main/pipeline/pipeline_PowerPaint_Brushnet_CA.py#L424
```

value of t and t_nag [incoming value](https://github.com/open-mmlab/PowerPaint/blob/main/gradio_PowerPaint_BrushNet.py#L198-L199) are the same, in my opinion, when the value of t increases, the weight of the shape in prompt becomes larger, and the weight of the shape in negative_prompt should become smaller, that is, t_neg = 1-t is correct. Is this written wrong in the code or I don't understand it?

Hope to get your answer.

**Comment by zengyh1900** [comment]
Hi @WenmuZhou,

Thank you for your interest and patience. This is an interesting question.

1. The version in our paper is built upon a fine-tuned UNet version, in which there is only one cross-attention mechanism for taking conditions. Regarding PowerPaint-V2 in our code, it is built upon BrushNet, which is plugged into an SD model. Therefore, for CFG sampling, we input the same prompt `P_obj` for both the positive (conditional) and the negative (unconditional) branches in BrushNet. In contrast, we input a description of the object for the conditional branch and null-text for the unconditional branch in the SD UNet.

2. The situation is similar in the shape-guided implementation in BrushNet. We input the same task prompts for both the conditional and unconditional branches in BrushNet, while using an object description for the conditional branch and null-text for the unconditional branch in SD.

I hope this clarifies things a bit.
