### ISSUE TITLE
encounter a problem when downloading model

### ISSUE THREAD

**Issue by ThisRookie** [open-mmlab/PowerPaint#45]
Use `git lfs logs last` to view the log.
cannot replace "/workspace/PowerPaint_v2/.git/lfs/objects/af/a7/afa7ebf10b23008ecbb81111e9cc8818443e1302a0defaa0a6cbd8cfe310b278" with "/workspace/PowerPaint_v2/.git/lfs/incomplete/afa7ebf10b23008ecbb81111e9cc8818443e1302a0defaa0a6cbd8cfe310b2782224200049": rename /workspace/PowerPaint_v2/.git/lfs/incomplete/afa7ebf10b23008ecbb81111e9cc8818443e1302a0defaa0a6cbd8cfe310b2782224200049 /workspace/PowerPaint_v2/.git/lfs/objects/af/a7/afa7ebf10b23008ecbb81111e9cc8818443e1302a0defaa0a6cbd8cfe310b278: no such file or directory
cannot replace "/workspace/PowerPaint_v2/.git/lfs/objects/c8/da/c8dac118ff5749ca65298f1546ec23d3fec876cded41f9559fcd863e30d969f4" with "/workspace/PowerPaint_v2/.git/lfs/incomplete/c8dac118ff5749ca65298f1546ec23d3fec876cded41f9559fcd863e30d969f4786515391": rename /workspace/PowerPaint_v2/.git/lfs/incomplete/c8dac118ff5749ca65298f1546ec23d3fec876cded41f9559fcd863e30d969f4786515391 /workspace/PowerPaint_v2/.git/lfs/objects/c8/da/c8dac118ff5749ca65298f1546ec23d3fec876cded41f9559fcd863e30d969f4: no such file or directory
cannot replace "/workspace/PowerPaint_v2/.git/lfs/objects/74/5a/745a3babce414c8b765c57e86412544cecdbdb0601648900d10b482256babb76" with "/workspace/PowerPaint_v2/.git/lfs/incomplete/745a3babce414c8b765c57e86412544cecdbdb0601648900d10b482256babb76465739092": rename /workspace/PowerPaint_v2/.git/lfs/incomplete/745a3babce414c8b765c57e86412544cecdbdb0601648900d10b482256babb76465739092 /workspace/PowerPaint_v2/.git/lfs/objects/74/5a/745a3babce414c8b765c57e86412544cecdbdb0601648900d10b482256babb76: no such file or directory
error: failed to fetch some objects from 'https://code.openxlab.org.cn/zhuangjunhao/PowerPaint_v2.git/info/lfs'
Not in a git repository.

**Comment by zengyh1900** [comment]
Hi @ThisRookie 
I think you should install git-lfs first. You can run the following command to install it, 
```shell
conda install git-lfs
git lfs install
```

BTW, we have updated [readme](https://github.com/open-mmlab/PowerPaint) to provide a more user-friendly introduction :)
