### ISSUE TITLE
textual inverison ?

### ISSUE THREAD

**Issue by viperyl** [open-mmlab/PowerPaint#47]
Are  P_ctxt, P_obj, P_shape these three are actually textual inversion?

the textual inversion binding "ID" to text embedding, and power paint binding "task" to text embedding. power paint trained a new textual inversion and finetune the unet. am i misunderstanding?

**Comment by zengyh1900** [comment]
Hi @viperyl,

Thanks for your interests! You're right! 
And, the only different part compared with textual inversion is that, textual inversion is often used for concept learning (e.g., pet dog, cat, toy, etc.) and we use it for task learning in PowerPaint, which correlates different task patterns with specific text embedding.
