### ISSUE TITLE
请问如何实现的Outpainting扩图，具体的实现方法在哪，想借鉴一些

### ISSUE THREAD

**Issue by hjj-lmx** [open-mmlab/PowerPaint#48]

**Comment by zengyh1900** [comment]
hi @hjj-lmx 

1. 如果是指推理的话，我们更新了 readme，有关于如何使用 outpainting 的介绍，[看这里](https://github.com/open-mmlab/PowerPaint?tab=readme-ov-file#image-outpainting)
2. 如果是特指训练，outpainting 的训练没有什么不同，最主要的是 mask 的生成，需要是图像外面一圈的mask
