### ISSUE TITLE
Questions about training and data prepare

### ISSUE THREAD

**Issue by majiajiong** [open-mmlab/PowerPaint#49]
I want to train a Brushnet similar to PowerPaintV2. If i use the text_encoder from PowerPaintV2, what should i prepare data ?

1. When using random mask, the prompt input for Brushnet is "P_ctxt"?
2. When using segmentation mask, the prompt input for Brushnet is "P_obj"?
3. The Unet part of basemodel is frozen and the prompt input is the whole image caption?

Should i put the image caption to Brushnet?

**Comment by zengyh1900** [comment]
hi @majiajiong 
thank you for your interest. 
1. Yes
2. Yes
3. The UNet is frozen, and its input depends on the training strategy. Sometimes, the input for UNet may be dropped.

We have released our training configuration, implementation of datasets and training scripts in [dev branch](https://github.com/open-mmlab/PowerPaint/tree/dev?tab=readme-ov-file#training). Hope it helps!
