### ISSUE TITLE
It seems that UNet and VAE are missing from the PowerPaint v2-1 model

### ISSUE THREAD

**Issue by hjj-lmx** [open-mmlab/PowerPaint#50]

**Comment by zengyh1900** [comment]
hi @hjj-lmx, 

we have checked it and update our readme with more detailed introduction steps. 
Please check it again. BTW, further discussion is always welcomed :)

**Comment by hjj-lmx** [comment]
> 你好@hjj-lmx，
> 
> 我们已经检查过了，并且更新了我们的 readme 文件，添加了更详细的介绍步骤。 请再检查一遍。顺便说一句，欢迎进一步讨论 :)

![1719557253(1)](https://github.com/open-mmlab/PowerPaint/assets/107909464/5981336a-d867-4e72-852f-7cb56cc1b9ed)
Isn't there no model here?
Not V2, but V2-1

**Comment by hjj-lmx** [comment]
> hi @hjj-lmx,
> 
> we have checked it and update our readme with more detailed introduction steps. Please check it again. BTW, further discussion is always welcomed :)

I also encountered a problem where the original part of the image that was generated using "image out painting" seems to have been changed. Is there a way to solve this problem?

> 你好@hjj-lmx，
> 
> 我们已经检查过了，并且更新了我们的 readme 文件，添加了更详细的介绍步骤。 请再检查一遍。顺便说一句，欢迎进一步讨论 :)

I also encountered a problem where the original part of the image that was generated using "image out painting" seems to have been changed. Is there a way to solve this problem?
