### ISSUE TITLE
In the image outputting function, the following code will cause the returned image to become smaller and blurry

### ISSUE THREAD

**Issue by hjj-lmx** [open-mmlab/PowerPaint#51]
In the image outputting function, the following code will cause the returned image to become smaller and blurry

 if size1 < size2:
            input_image["image"] = input_image["image"].convert("RGB").resize((512, int(size2 / size1 * 512)))
        else:
            input_image["image"] = input_image["image"].convert("RGB").resize((int(size1 / size2 * 512), 512))
            
            
If deleted, the incoming image pixels will be too large and the generation speed will be slow

Is there any solution

**Comment by zengyh1900** [comment]
Hi @hjj-lmx, 

thanks for interest. Yes, it is hard to manage resolution and runtime speed at the same time. 
You may use less sampling steps and more advanced sampler or deployed tricks to accelerate it, which is currently not supported in our project.
