### ISSUE TITLE
Issue when running python app.py --share

### ISSUE THREAD

**Issue by danielscos** [open-mmlab/PowerPaint#54]
When I run it, it downloads a bunch of libraries and then at the end it says: AssertionError: Torch not compiled with CUDA enabled

How do I fix this?

**Comment by danielscos** [comment]
(ppt) C:\Users\danie\OneDrive\Desktop\powerpaint>python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2
C:\Users\danie\anaconda3\envs\ppt\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
unet/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 743/743 [00:00<00:00, 371kB/s]
C:\Users\danie\anaconda3\envs\ppt\lib\site-packages\huggingface_hub\file_download.py:157: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\danie\.cache\huggingface\hub\models--runwayml--stable-diffusion-v1-5. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
diffusion_pytorch_model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.44G/3.44G [04:56<00:00, 11.6MB/s]
text_encoder/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 617/617 [00:00<00:00, 309kB/s]
model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 492M/492M [00:44<00:00, 11.1MB/s]
Traceback (most recent call last):
  File "C:\Users\danie\OneDrive\Desktop\powerpaint\app.py", line 560, in <module>
    controller = PowerPaintController(weight_dtype, args.checkpoint_dir, args.local_files_only, args.version)
  File "C:\Users\danie\OneDrive\Desktop\powerpaint\app.py", line 157, in __init__
    self.pipe = StableDiffusionPowerPaintBrushNetPipeline.from_pretrained(
  File "C:\Users\danie\anaconda3\envs\ppt\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\danie\anaconda3\envs\ppt\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 671, in from_pretrained
    cached_folder = cls.download(
  File "C:\Users\danie\anaconda3\envs\ppt\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\danie\anaconda3\envs\ppt\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1205, in download
    info = model_info(pretrained_model_name, token=token, revision=revision)
  File "C:\Users\danie\anaconda3\envs\ppt\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\danie\anaconda3\envs\ppt\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'checkpoints/ppt-v2\realisticVisionV60B1_v51VAE'.

this is what happens when i run python app.py --share --version ppt-v2 --checkpoint_dir checkpoints/ppt-v2

**Comment by zengyh1900** [comment]
Oh @danielscos thanks for pointing out this issue. It is my bad. I will fix it today.

**Comment by danielscos** [comment]
Ok 😆

**Comment by danielscos** [comment]
> Oh @danielscos thanks for pointing out this issue. It is my bad. I will fix it today.

@zengyh1900 please tell me when you do fix it

**Comment by danielscos** [comment]
> Oh @danielscos thanks for pointing out this issue. It is my bad. I will fix it today.

Is It fixed yet?

**Comment by danielscos** [comment]
> Oh @danielscos thanks for pointing out this issue. It is my bad. I will fix it today.

So, is it fixed yet?

**Comment by zengyh1900** [comment]
Hi @danielscos 

:sob: :sob: I apologize for the oversight regarding the message associated with this issue. Additionally, I appreciate your patience throughout this process.

Firstly, the cause of the bug is that the diffusers pipeline typically checks for the model path from [huggingface/models](https://huggingface.co/models), but in this case, we have provided a local path instead of a URL. Consequently, when it attempts to check the path, it raises an error stating that it cannot parse the URL.

To resolve this issue, you can simply add the parameter `local_files_only=True` to the function call, i.e., 
from 
```
self.pipe = StableDiffusionPowerPaintBrushNetPipeline.from_pretrained(
                base_model_path,
                brushnet=brushnet,
                text_encoder_brushnet=text_encoder_brushnet,
                torch_dtype=weight_dtype,
                low_cpu_mem_usage=False,
                safety_checker=None,
            )
```
to 
```
self.pipe = StableDiffusionPowerPaintBrushNetPipeline.from_pretrained(
                base_model_path,
                brushnet=brushnet,
                text_encoder_brushnet=text_encoder_brushnet,
                torch_dtype=weight_dtype,
                low_cpu_mem_usage=False,
                safety_checker=None,
                local_files_only=True
            )
```
