### ISSUE TITLE
Inference Speed

### ISSUE THREAD

**Issue by EveWYT** [open-mmlab/PowerPaint#56]
I have successfully run ppt-v2, but I noticed that it takes about 15 minutes to inpaint a single image. Is this normal? Are there any ways to speed it up? I am currently using the GPU version of PyTorch.

**Comment by zengyh1900** [comment]
hi @EveWYT 
15 minutes is unnormal. It usually takes 20 seconds to inpaint an image on an A100 GPU, and I guess running on 4090 won't show an obvious difference.
