### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by XiruiTeng** [open-mmlab/PowerPaint#57]
Thanks for your work! But I met an error when I ran the python app.py. It said "Error Expecting value: line 1 column 1 (char 0)". Can you help me fix this problem?

**Comment by zengyh1900** [comment]
can you share the whole command you ran?

**Comment by XiruiTeng** [comment]
> can you share the whole command you ran?

I enter the command 'python app.py --share'. After opening the web, I uploaded the image and gave a prompt and it gave an error. 
<img width="1198" alt="截屏2024-07-04 14 01 21" src="https://github.com/open-mmlab/PowerPaint/assets/131317640/8edd0eae-8e42-4afb-9526-e215ba454c34">

**Comment by Chinafsh** [comment]
> > can you share the whole command you ran?
> 
> I enter the command 'python app.py --share'. After opening the web, I uploaded the image and gave a prompt and it gave an error. <img alt="截屏2024-07-04 14 01 21" width="1198" src="https://private-user-images.githubusercontent.com/131317640/345714190-8edd0eae-8e42-4afb-9526-e215ba454c34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTU2NzksIm5iZiI6MTcyNDk5NTM3OSwicGF0aCI6Ii8xMzEzMTc2NDAvMzQ1NzE0MTkwLThlZGQwZWFlLThlNDItNGFmYi05NTI2LWUyMTViYTQ1NGMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNTIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmU0OGY4NWMwNzcxYzNmYWI3Y2M5ZmZhNDFhY2NiYmVhMGFiYWMyMGMyZTM4NDA5NTE2ZmQ2OTkyYjQ3ZTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eogGtrar73YB2-KKrkdoucbdEAAYjLYXEBirPf4r3pU">

Hello, I got the same problem with u, do u know how to solve it? thx!

**Comment by XiruiTeng** [comment]
> > > can you share the whole command you ran?
> > 
> > 
> > I enter the command 'python app.py --share'. After opening the web, I uploaded the image and gave a prompt and it gave an error. <img alt="截屏2024-07-04 14 01 21" width="1198" src="https://private-user-images.githubusercontent.com/131317640/345714190-8edd0eae-8e42-4afb-9526-e215ba454c34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTU2NzksIm5iZiI6MTcyNDk5NTM3OSwicGF0aCI6Ii8xMzEzMTc2NDAvMzQ1NzE0MTkwLThlZGQwZWFlLThlNDItNGFmYi05NTI2LWUyMTViYTQ1NGMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNTIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmU0OGY4NWMwNzcxYzNmYWI3Y2M5ZmZhNDFhY2NiYmVhMGFiYWMyMGMyZTM4NDA5NTE2ZmQ2OTkyYjQ3ZTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eogGtrar73YB2-KKrkdoucbdEAAYjLYXEBirPf4r3pU">
> 
> Hello, I got the same problem with u, do u know how to solve it? thx!

sry, i don't know

**Comment by Chinafsh** [comment]
> > > > can you share the whole command you ran?
> > > 
> > > 
> > > I enter the command 'python app.py --share'. After opening the web, I uploaded the image and gave a prompt and it gave an error. <img alt="截屏2024-07-04 14 01 21" width="1198" src="https://private-user-images.githubusercontent.com/131317640/345714190-8edd0eae-8e42-4afb-9526-e215ba454c34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTU2NzksIm5iZiI6MTcyNDk5NTM3OSwicGF0aCI6Ii8xMzEzMTc2NDAvMzQ1NzE0MTkwLThlZGQwZWFlLThlNDItNGFmYi05NTI2LWUyMTViYTQ1NGMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNTIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmU0OGY4NWMwNzcxYzNmYWI3Y2M5ZmZhNDFhY2NiYmVhMGFiYWMyMGMyZTM4NDA5NTE2ZmQ2OTkyYjQ3ZTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eogGtrar73YB2-KKrkdoucbdEAAYjLYXEBirPf4r3pU">
> > 
> > 
> > Hello, I got the same problem with u, do u know how to solve it? thx!
> 
> sry, i don't know

Actually, I write some codes in this work, i.e. “result.show(), or result.save()” to get the inpainting result. It works for me.

**Comment by zengyh1900** [comment]
Hi @XiruiTeng , @Chinafsh, 

I'm sorry I can't reproduce this problem :( 
I guess it can be raised when you are using a VPN or proxy. You can have a try after turning off VPN.
