### ISSUE TITLE
How should the model of this parameter be called

### ISSUE THREAD

**Issue by hjj-lmx** [open-mmlab/PowerPaint#60]
StableDiffusionPowerPaintBrushNetPipeline.from_pretrained(
            base_model_path,
            brushnet=brushnet,
            text_encoder_brushnet=text_encoder_brushnet,
            torch_dtype=dtype,
            low_cpu_mem_usage=False,
            safety_checker=None,
        )
   safety_checker=None,      
How should the model of this parameter be called？

**Comment by zengyh1900** [comment]
Hi @hjj-lmx, 

We have provided codes for its usage of [initialization](https://github.com/open-mmlab/PowerPaint/blob/main/app.py#L157) and [forward](https://github.com/open-mmlab/PowerPaint/blob/main/app.py#L346). You can also refer to its [source implementation](https://github.com/open-mmlab/PowerPaint/blob/main/powerpaint/pipelines/pipeline_PowerPaint_Brushnet_CA.py) for more details.
