### ISSUE TITLE
question about text prompt

### ISSUE THREAD

**Issue by SmileTAT** [open-mmlab/PowerPaint#63]
Q1: Are the segmentation labels (cat, dot, flower, etc.) used as text prompt in the training set?
Q2: If the answer to Q1 is yes, can the model accept complex text (`a white cat`, `two running yellow dogs`)?

**Comment by zengyh1900** [comment]
hi @SmileTAT 
Q1. YES
Q2. YES

However, since Powerpaint is trained with simple text prompts (which often describe single objects), therefore, extremely complex text prompts involving multiple attributes and objects can be challenging.
