### ISSUE TITLE
Issue when running python app.py --share

### ISSUE THREAD

**Issue by ankitatiisc** [open-mmlab/PowerPaint#66]
When I run command 
`python app.py --share`

I am getting following error:
```
raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-66b3c1b1-3e4783ad3150978f3308bc5c;404e2553-e85f-4195-aaa1-e0d996dbb8bf)
Entry Not Found for url: https://huggingface.co/lllyasviel/ControlNet/resolve/main/ControlNetHED.pth.
```

When I paste this URL as it is on browser, it says entry is not found.

**Comment by Chinafsh** [comment]
I got same problem,do u know how to do it?

**Comment by Chinafsh** [comment]
> When I run command `python app.py --share`
> 
> I am getting following error:
> 
> ```
> raise EntryNotFoundError(message, response) from e
> huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-66b3c1b1-3e4783ad3150978f3308bc5c;404e2553-e85f-4195-aaa1-e0d996dbb8bf)
> Entry Not Found for url: https://huggingface.co/lllyasviel/ControlNet/resolve/main/ControlNetHED.pth.
> ```
> 
> When I paste this URL as it is on browser, it says entry is not found.

Do u know how to solve it? thx

**Comment by zengyh1900** [comment]
hi @ankitatiisc , @Chinafsh 

I appreciate your interest. Would you mind providing more error messages because I can't reproduce this problem?
Besides, I have checked that we actually use `lllyasviel/sd-controlnet-hed` in our codes instead of  `ControlNetHED.pth`

**Comment by Chinafsh** [comment]
> hi @ankitatiisc , @Chinafsh
> 
> I appreciate your interest. Would you mind providing more error messages because I can't reproduce this problem? Besides, I have checked that we actually use `lllyasviel/sd-controlnet-hed` in our codes instead of `ControlNetHED.pth`

thx for u reply. Actually, I find it's not a big problem, I changed the url from "https://huggingface.co/....." to "https://hf-mirror.co/.....".
