### ISSUE TITLE
请问是否有开源训练代码的计划？

### ISSUE THREAD

**Issue by lucDoom** [open-mmlab/PowerPaint#68]
如题，感谢感谢

**Comment by zengyh1900** [comment]
Hi @lucDoom，

有的。finetune unet 方案和基于 brushnet 的这种外插的方式，这两种训练代码都会公开。

**Comment by zengyh1900** [comment]
@lucDoom 这周就会开源，在整理中。

**Comment by WM-Wu** [comment]
期待开源

**Comment by zhLawliet** [comment]
@zengyh1900 请问下，这周会开源吗？

**Comment by zhLawliet** [comment]
> @lucDoom 这周就会开源，在整理中。

@zengyh1900 请问下，这周会开源吗？

**Comment by RunpuWei** [comment]
请问大概多久开源训练代码呢，以及是否有官方支持SDXL的计划
