### ISSUE TITLE
MMCV error

### ISSUE THREAD

**Issue by Echolink50** [open-mmlab/PowerPaint#7]
Getting a no module named MMCV error. Ran pip install MMCV but then it said 2.1.0 was too new so I tried to install 2.0.0 and couldn't. Any help? Thanks

**Comment by saidattax** [comment]
Same. Fresh clone of repo not working in venv

```
python gradio_PowerPaint.py
```

```
Traceback (most recent call last):
  File "/workspace/PowerPaint/gradio_PowerPaint.py", line 15, in <module>
    from utils.utils import TokenizerWrapper, add_tokens
  File "/workspace/PowerPaint/utils/utils.py", line 12, in <module>
    from mmagic.utils import try_import
  File "/workspace/PowerPaint/lauda/lib/python3.10/site-packages/mmagic/__init__.py", line 2, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
```

**Comment by Echolink50** [comment]
I eventually got it working.Windows 10, Xeon 1240v5, 16GB Ram, RTX 2060 12GB.VRam. Installed VS 2022 and Cuda Toolkit 12.2. What system are you on? Not sure what the prerequisites are but make sure you have visual studio and Cuda installed with the proper environment variable paths. After you create the environment and activate it make sure you have pytorch installed before running the requirements.txt file. For me this command worked.

"conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia"

Good luck

**Comment by saidattax** [comment]
> it was the MMagic repo I got working

What is the MMagic repo ?

**Comment by Echolink50** [comment]
Yes that's it. Let's us know if you get it working

**Comment by alexgilseg** [comment]
This is driving me crazy.. Any of you had this error?

```
(PowerPaint) D:\SDXL\PowerP\PowerPaint>python gradio_PowerPaint.py
Traceback (most recent call last):
  File "D:\SDXL\PowerP\PowerPaint\gradio_PowerPaint.py", line 15, in <module>
    from utils.utils import TokenizerWrapper, add_tokens
  File "D:\SDXL\PowerP\PowerPaint\utils\utils.py", line 12, in <module>
    from mmagic.utils import try_import
  File "C:\Users\alexg\anaconda3\envs\PowerPaint\lib\site-packages\mmagic\__init__.py", line 35, in <module>
    assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
AssertionError: mmcv==2.1.0 is used but incompatible. Please install mmcv-full>=[2, 0, 0], <[2, 1, 0].
```

**Comment by Echolink50** [comment]
> This is driving me crazy.. Any of you had this error?
> 
> ```
> (PowerPaint) D:\SDXL\PowerP\PowerPaint>python gradio_PowerPaint.py
> Traceback (most recent call last):
>   File "D:\SDXL\PowerP\PowerPaint\gradio_PowerPaint.py", line 15, in <module>
>     from utils.utils import TokenizerWrapper, add_tokens
>   File "D:\SDXL\PowerP\PowerPaint\utils\utils.py", line 12, in <module>
>     from mmagic.utils import try_import
>   File "C:\Users\alexg\anaconda3\envs\PowerPaint\lib\site-packages\mmagic\__init__.py", line 35, in <module>
>     assert (mmcv_min_version <= mmcv_version < mmcv_max_version), \
> AssertionError: mmcv==2.1.0 is used but incompatible. Please install mmcv-full>=[2, 0, 0], <[2, 1, 0].
> ```

Yeah I had that one a few times. I would start with a fresh install and a fresh condo env. Maybe even clear out the pip cache. Sometimes it will keep trying to install the same files that didnt work before from cache. Make sure you have pytorch installed before running the requirements.txt file.

**Comment by alexgilseg** [comment]
I've been doing that all day.. Trying all sorts of things.. I don't even know if the program is any good lol.. I just hate when I can't get things right.. Is it worth it ?

**Comment by Echolink50** [comment]
> I've been doing that all day.. Trying all sorts of things.. I don't even know if the program is any good lol.. I just hate when I can't get things right.. Is it worth it ?

I guess it depends on what you're trying to do. But if you're interested in inpainting and outpainting you might try Fooocus first and see if it will do what you want. It's an easy auto installer. PowerPaint is good too but I just install all of them and use different ones for different purposes. Good luck

**Comment by alexgilseg** [comment]
I am mainly after outpainting actually.. I'll give fooocus a go but my autistic brain won't let me give up on this.. I'm trying the other repo now.. how did you end up getting the correct version of mmcv?

mim install mmcv==2.0.0

??

**Comment by Echolink50** [comment]
> I am mainly after outpainting actually.. I'll give fooocus a go but my autistic brain won't let me give up on this.. I'm trying the other repo now.. how did you end up getting the correct version of mmcv?
> 
> mim install mmcv==2.0.0
> 
> ??

It's been almost a month since I installed it so I honestly can't remember. But maybe some type of pip install MMCV or something like that. Seemed like as long as I had the right environment set up in the right pytorch it seemed to have worked when I installed the requirements. Also like I said make sure you're using the mmagic repo. I never got this one to work. Sorry I couldn't be more help.

**Comment by tranquan687** [comment]
try this, it works for me
https://github.com/zhuang2002/PowerPaint/issues/23#issue-2206231108

**Comment by zengyh1900** [comment]
all dependencies of `mmcv` and `mmengine` have been removed.

**Comment by aminakmim** [comment]
@zengyh1900 I am getting this error from main branch 

> ModuleNotFoundError: No module named 'mmengine'

Is the update in dev branch ?
